"""Tablas de referencia territorial de España.

- CCAA_POR_CODAUTO: código CODAUTO del INE (01-19) -> (ISO 3166-2, nombre).
- PROVINCIA_POR_CPRO: código de provincia del INE (01-52) -> nombre.
"""

# CODAUTO (INE) -> (código ISO 3166-2:ES, nombre de la comunidad/ciudad autónoma)
CCAA_POR_CODAUTO = {
    "01": ("ES-AN", "Andalucía"),
    "02": ("ES-AR", "Aragón"),
    "03": ("ES-AS", "Principado de Asturias"),
    "04": ("ES-IB", "Illes Balears"),
    "05": ("ES-CN", "Canarias"),
    "06": ("ES-CB", "Cantabria"),
    "07": ("ES-CL", "Castilla y León"),
    "08": ("ES-CM", "Castilla-La Mancha"),
    "09": ("ES-CT", "Cataluña"),
    "10": ("ES-VC", "Comunitat Valenciana"),
    "11": ("ES-EX", "Extremadura"),
    "12": ("ES-GA", "Galicia"),
    "13": ("ES-MD", "Comunidad de Madrid"),
    "14": ("ES-MC", "Región de Murcia"),
    "15": ("ES-NC", "Comunidad Foral de Navarra"),
    "16": ("ES-PV", "País Vasco"),
    "17": ("ES-RI", "La Rioja"),
    "18": ("ES-CE", "Ceuta"),
    "19": ("ES-ML", "Melilla"),
}

# Código de provincia (CPRO, INE) -> nombre oficial de la provincia
PROVINCIA_POR_CPRO = {
    "01": "Araba/Álava",
    "02": "Albacete",
    "03": "Alicante/Alacant",
    "04": "Almería",
    "05": "Ávila",
    "06": "Badajoz",
    "07": "Illes Balears",
    "08": "Barcelona",
    "09": "Burgos",
    "10": "Cáceres",
    "11": "Cádiz",
    "12": "Castellón/Castelló",
    "13": "Ciudad Real",
    "14": "Córdoba",
    "15": "A Coruña",
    "16": "Cuenca",
    "17": "Girona",
    "18": "Granada",
    "19": "Guadalajara",
    "20": "Gipuzkoa",
    "21": "Huelva",
    "22": "Huesca",
    "23": "Jaén",
    "24": "León",
    "25": "Lleida",
    "26": "La Rioja",
    "27": "Lugo",
    "28": "Madrid",
    "29": "Málaga",
    "30": "Murcia",
    "31": "Navarra",
    "32": "Ourense",
    "33": "Asturias",
    "34": "Palencia",
    "35": "Las Palmas",
    "36": "Pontevedra",
    "37": "Salamanca",
    "38": "Santa Cruz de Tenerife",
    "39": "Cantabria",
    "40": "Segovia",
    "41": "Sevilla",
    "42": "Soria",
    "43": "Tarragona",
    "44": "Teruel",
    "45": "Toledo",
    "46": "Valencia/València",
    "47": "Valladolid",
    "48": "Bizkaia",
    "49": "Zamora",
    "50": "Zaragoza",
    "51": "Ceuta",
    "52": "Melilla",
}
